# Generated by Django 5.1.2 on 2024-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_logo_key', models.CharField(blank=True, max_length=255, null=True)),
                ('physician_name', models.CharField(max_length=255)),
                ('physician_contact', models.CharField(max_length=255)),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_last_name', models.CharField(max_length=255)),
                ('patient_dob', models.DateField()),
                ('patient_contact', models.CharField(max_length=255)),
                ('chief_complaint', models.TextField(max_length=5000)),
                ('consultation_note', models.TextField(max_length=5000)),
            ],
        ),
    ]
